platform :ios, '8.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'Cypherpunk' do
       pod 'ReSwift'
       pod 'SwiftyStoreKit'
       pod 'APIKit'
       pod 'Himotoki'
       pod 'R.swift', '~> 2.5.0'
       pod 'ReachabilitySwift'
       pod 'KeychainAccess', '~> 2.3.6'
       pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
       pod 'RealmSwift'
       pod 'UITextView+Placeholder', '~> 1.2'
       pod 'MZFormSheetPresentationController'
end

target 'CypherpunkTests' do
       pod 'ReSwift'
       pod 'APIKit'
       pod 'Himotoki'
       pod 'R.swift', '~> 2.5.0'
end

target 'CypherpunkUITests' do
       pod 'ReSwift'
       pod 'APIKit'
       pod 'Himotoki'
       pod 'R.swift', '~> 2.5.0'
       pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
end

