platform :ios, '8.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'Cypherpunk' do
       pod 'ReSwift'
       pod 'SwiftyStoreKit'
end

target 'CypherpunkTests' do
       pod 'ReSwift'
end

target 'CypherpunkUITests' do
       pod 'ReSwift'
end

